import logging
import pytest

from scraper import validate_movie_params

# Generated by ChatGPT
def test_validate_movie_params_success():
    # Test that the function works correctly when all parameters are valid
    top_nr_to_take = 3
    movie_titles = ["Movie 1", "Movie 2", "Movie 3"]
    ratings = [8.5, 9.0, 7.8]
    nr_of_votes = [100, 200, 50]
    nr_of_oscars = [1, 0, 2]
    logger = logging.getLogger()
    validate_movie_params(top_nr_to_take, movie_titles, ratings, nr_of_votes, nr_of_oscars, logger)

def test_validate_movie_params_missing_params():
    # Test that the function raises an exception when any parameter is missing
    top_nr_to_take = 3
    movie_titles = ["Movie 1", "Movie 2"]
    ratings = [8.5, 9.0, 7.8]
    nr_of_votes = [100, 200, 50]
    nr_of_oscars = [1, 0, 2]
    logger = logging.getLogger()
    with pytest.raises(AssertionError):
        validate_movie_params(top_nr_to_take, movie_titles, ratings, nr_of_votes, nr_of_oscars, logger)

def test_validate_movie_params_more_params():
    # Test that the function raises an exception when any parameter has the wrong number of elements
    top_nr_to_take = 3
    movie_titles = ["Movie 1", "Movie 2", "Movie 3", "Movie 4"]
    ratings = [8.5, 9.0, 7.8]
    nr_of_votes = [100, 200, 50]
    nr_of_oscars = [1, 0, 2]
    logger = logging.getLogger()
    with pytest.raises(AssertionError):
        validate_movie_params(top_nr_to_take, movie_titles, ratings, nr_of_votes, nr_of_oscars, logger)
